webdriver.driver = edge


#webdriver.executable.path = msedgedriver.exe

headless.mode = false
serenity.browser.maximized=true
serenity.take.screenshots = AFTER_EACH_STEP
webdriver.base.url=https://www.ebay.com
webdriver.edge.args = --start-maximized --inprivate --disable-popup-blocking --disable-notifications
